name: Get diff of bun.lockb and comment on PR
description: Get started with Composite actions
branding:
  icon: award
  color: green
inputs:
  lockb-path:
    description: 'Path to bun.lockb'
    required: false
    default: './bun.lockb'
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: composite
  steps:
    - name: Check if Bun is installed
      shell: bash -e {0}
      run: |
        if ! command -v bun &> /dev/null
        then
            echo "Bun could not be found"
            exit 1
        fi

    - name: Get diff of bun.lockb and comment on PR
      shell: bash -e {0}
      run: |
        echo "*.lockb binary diff=lockb" > .gitattributes
        git config diff.lockb.textconv bun
        git config diff.lockb.binary true
        git fetch origin ${{ github.event.pull_request.base.ref }}
        git fetch origin ${{ github.event.pull_request.head.ref }}
        echo "```diff" > diff.txt
        git diff --no-color origin/main origin/feature/add-unknownutil -- ${{ inputs.lockb-path }} > diff.txt
        echo "```" >> diff.txt

    - name: Comment Diff on PR
      shell: bash -e {0}
      run: |
        if [ -s diff.txt ]; then
          gh pr comment \
            ${{ github.event.pull_request.number }} \
            -F diff.txt 
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}



