name: Get diff of bun.lockb and comment on PR
description: Get started with Composite actions
branding:
  icon: award
  color: green
inputs:
  lockb-path:
    description: 'Path to bun.lockb'
    required: false
    default: './bun.lockb'
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: composite
  steps:
    - name: Check if Bun is installed
      shell: bash -e {0}
      run: |
        if ! command -v bun &> /dev/null
        then
            echo "Bun could not be found"
            exit 1
        fi

    - name: Get diff of bun.lockb and comment on PR
      id: bun_lockb_diff
      shell: bash -e {0}
      run: |
        echo "*.lockb binary diff=lockb" > .gitattributes
        git config diff.lockb.textconv bun
        git config diff.lockb.binary true
        echo "diff=$(git diff --no-color ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }} -- ${{ inputs.lockb-path }})" >> "$GITHUB_OUTPUT"

    - name: Comment Diff on PR
      shell: bash -e {0}
      run: |
        if [[ -n "${{ steps.bun_lockb_diff.outputs.diff }}" ]]; then
          gh pr comment \
            ${{ github.event.pull_request.number }} \
            --body "$(cat ${{ steps.bun_lockb_diff.outputs.diff }})" \
            --edit-last
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}



