name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: ./
        with:
          lockb-path: ./bun.lockb
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
