name: Test

on:
  pull_request:
  workflow_dispatch:

permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: ./
        with:
          lockb-path: ./tests/bun_project/bun.lockb
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
